### ISSUE TITLE
Tag releases on GitHub

### ISSUE THREAD

**Issue by jluttine** [delfick/nose-focus#5]
Could you tag the PyPI releases on the git repo too? I'm packaging nose-focus for a Linux distro but the PyPI tarball doesn't contain the tests so I would need to use the git repo but it'd be great if the versions were tagged in GitHub so I can get the exact correct commit corresponding to the release.

**Comment by delfick** [comment]
Sure, I can do that :)

**Comment by delfick** [comment]
I've made a release for the current version, https://github.com/delfick/nose-focus/releases
